export const FETCH_ADMIN_ORDERS_LOADING = "FETCH_ADMIN_ORDERS_LOADING";
export const FETCH_ADMIN_ORDERS_SUCCESS = "FETCH_ADMIN_ORDERS_SUCCESS";
export const FETCH_ADMIN_ORDERS_ERROR = "FETCH_ADMIN_ORDERS_ERROR";
export const FETCH_ADMIN_ORDERS_RESET = "FETCH_ADMIN_ORDERS_RESET";

export const FETCH_ADMIN_ORDER_LOADING = "FETCH_ADMIN_ORDER_LOADING";
export const FETCH_ADMIN_ORDER_SUCCESS = "FETCH_ADMIN_ORDER_SUCCESS";
export const FETCH_ADMIN_ORDER_ERROR = "FETCH_ADMIN_ORDER_ERROR";
export const FETCH_ADMIN_ORDER_RESET = "FETCH_ADMIN_ORDER_RESET";

export const UPDATE_ADMIN_ORDER_LOADING = "UPDATE_ADMIN_ORDER_LOADING";
export const UPDATE_ADMIN_ORDER_SUCCESS = "UPDATE_ADMIN_ORDER_SUCCESS";
export const UPDATE_ADMIN_ORDER_ERROR = "UPDATE_ADMIN_ORDER_ERROR";
export const UPDATE_ADMIN_ORDER_RESET = "UPDATE_ADMIN_ORDER_RESET";
