export const LOGIN_USER_LOADING = "LOGIN_USER_LOADING";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_USER_RESET = "LOGIN_USER_RESET";

export const VARIFY_PHONE_LOADING = "VARIFY_PHONE_LOADING";
export const VARIFY_PHONE_SUCCESS = "VARIFY_PHONE_SUCCESS";
export const VARIFY_PHONE_ERROR = "VARIFY_PHONE_ERROR";
export const VARIFY_PHONE_RESET = "VARIFY_PHONE_RESET";

export const CONFIRM_OTP_LOADING = "CONFIRM_OTP_LOADING";
export const CONFIRM_OTP_SUCCESS = "CONFIRM_OTP_SUCCESS";
export const CONFIRM_OTP_ERROR = "CONFIRM_OTP_ERROR";
export const CONFIRM_OTP_RESET = "CONFIRM_OTP_RESET";

export const UPDATE_USER_LOADING = "UPDATE_USER_LOADING";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";

export const CREATE_BIZ_LOADING = "CREATE_BIZ_LOADING";
export const CREATE_BIZ_SUCCESS = "CREATE_BIZ_SUCCESS";
export const CREATE_BIZ_ERROR = "CREATE_BIZ_ERROR";
export const CREATE_BIZ_RESET = "CREATE_BIZ_RESET";

export const UPDATE_BIZ_LOADING = "UPDATE_BIZ_LOADING";
export const UPDATE_BIZ_SUCCESS = "UPDATE_BIZ_SUCCESS";
export const UPDATE_BIZ_ERROR = "UPDATE_BIZ_ERROR";
export const UPDATE_BIZ_RESET = "UPDATE_BIZ_RESET";
