export const LOGIN_USER_LOADING = "LOGIN_USER_LOADING";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_USER_RESET = "LOGIN_USER_RESET";

export const VARIFY_EMAIL_LOADING = "VARIFY_EMAIL_LOADING";
export const VARIFY_EMAIL_SUCCESS = "VARIFY_EMAIL_SUCCESS";
export const VARIFY_EMAIL_ERROR = "VARIFY_EMAIL_ERROR";
export const VARIFY_EMAIL_RESET = "VARIFY_EMAIL_RESET";