export const GET_CART_LOADING = "GET_CART_LOADING";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_ERROR = "GET_CART_ERROR";
export const GET_CART_RESET = "GET_CART_RESET";

export const ADD_CART_LOADING = "ADD_CART_LOADING";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_ERROR = "ADD_CART_ERROR";
export const ADD_CART_RESET = "ADD_CART_RESET";

export const ADD_BAG_LOADING = "ADD_BAG_LOADING";
export const ADD_BAG_SUCCESS = "ADD_BAG_SUCCESS";
export const ADD_BAG_ERROR = "ADD_BAG_ERROR";
export const ADD_BAG_RESET = "ADD_BAG_RESET";

export const GET_BAG_LOADING = "GET_BAG_LOADING";
export const GET_BAG_SUCCESS = "GET_BAG_SUCCESS";
export const GET_BAG_ERROR = "GET_BAG_ERROR";
export const GET_BAG_RESET = "GET_BAG_RESET";

export const CHANGE_QTY_LOADING = "CHANGE_QTY_LOADING";
export const CHANGE_QTY_SUCCESS = "CHANGE_QTY_SUCCESS";
export const CHANGE_QTY_ERROR = "CHANGE_QTY_ERROR";
export const CHANGE_QTY_RESET = "CHANGE_QTY_RESET";

export const SELECT_CART_ITEM_LOADING = "SELECT_CART_ITEM_LOADING";
export const SELECT_CART_ITEM_SUCCESS = "SELECT_CART_ITEM_SUCCESS";
export const SELECT_CART_ITEM_ERROR = "SELECT_CART_ITEM_ERROR";
export const SELECT_CART_ITEM_RESET = "SELECT_CART_ITEM_RESET";

export const DELETE_CART_LOADING = "DELETE_CART_LOADING";
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export const DELETE_CART_ERROR = "DELETE_CART_ERROR";
export const DELETE_CART_RESET = "DELETE_CART_RESET";

export const GET_SHIPPING_INFO_LOADING = "GET_SHIPPING_INFO_LOADING";
export const GET_SHIPPING_INFO_SUCCESS = "GET_SHIPPING_INFO_SUCCESS";
export const GET_SHIPPING_INFO_ERROR = "GET_SHIPPING_INFO_ERROR";
export const GET_SHIPPING_INFO_RESET = "GET_SHIPPING_INFO_RESET";

export const ADD_SHIPPING_INFO_LOADING = "ADD_SHIPPING_INFO_LOADING";
export const ADD_SHIPPING_INFO_SUCCESS = "ADD_SHIPPING_INFO_SUCCESS";
export const ADD_SHIPPING_INFO_ERROR = "ADD_SHIPPING_INFO_ERROR";
export const ADD_SHIPPING_INFO_RESET = "ADD_SHIPPING_INFO_RESET";
