export const GET_CART_LOADING = "GET_CART_LOADING";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_ERROR = "GET_CART_ERROR";
export const GET_CART_RESET = "GET_CART_RESET";

export const ADD_CART_LOADING = "ADD_CART_LOADING";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_ERROR = "ADD_CART_ERROR";
export const ADD_CART_RESET = "ADD_CART_RESET";

export const EDIT_CART_LOADING = "EDIT_CART_LOADING";
export const EDIT_CART_SUCCESS = "EDIT_CART_SUCCESS";
export const EDIT_CART_ERROR = "EDIT_CART_ERROR";
export const EDIT_CART_RESET = "EDIT_CART_RESET";

export const DELETE_CART_LOADING = "DELETE_CART_LOADING";
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export const DELETE_CART_ERROR = "DELETE_CART_ERROR";
export const DELETE_CART_RESET = "DELETE_CART_RESET";
