export const FETCH_CATEGORY_LOADING = 'FETCH_CATEGORY_LOADING'
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS'
export const FETCH_CATEGORY_ERROR = 'FETCH_CATEGORY_ERROR'
export const FETCH_CATEGORY_RESET = 'FETCH_CATEGORY_RESET'
