export const SET_CONNECTION_SOCKET = "SET_CONNECTION_SOCKET";
export const RESET_CONNECTION_SOCKET = "SET_CONNECTION_SOCKET";

export const LOAD_MESSAGES_LOADING = "LOAD_MESSAGES_LOADING";
export const LOAD_MESSAGES_SUCCESS = "LOAD_MESSAGES_SUCCESS";
export const LOAD_MESSAGES_ERROR = "LOAD_MESSAGES_ERROR";
export const LOAD_MESSAGES_RESET = "LOAD_MESSAGES_RESET";

export const SEND_MESSAGE_LOADING = "SEND_MESSAGE_LOADING";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_ERROR = "SEND_MESSAGE_ERROR";
export const SEND_MESSAGE_RESET = "SEND_MESSAGE_RESET";
