export const PLACE_ORDER_LOADING = "PLACE_ORDER_LOADING";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_ERROR = "PLACE_ORDER_ERROR";
export const PLACE_ORDER_RESET = "PLACE_ORDER_RESET";

export const PAY_ORDER_LOADING = "PAY_ORDER_LOADING";
export const PAY_ORDER_SUCCESS = "PAY_ORDER_SUCCESS";
export const PAY_ORDER_ERROR = "PAY_ORDER_ERROR";
export const PAY_ORDER_RESET = "PAY_ORDER_RESET";
