export const PLACE_ORDER_LOADING = "PLACE_ORDER_LOADING";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_ERROR = "PLACE_ORDER_ERROR";
export const PLACE_ORDER_RESET = "PLACE_ORDER_RESET";

export const PAY_ORDER_LOADING = "PAY_ORDER_LOADING";
export const PAY_ORDER_SUCCESS = "PAY_ORDER_SUCCESS";
export const PAY_ORDER_ERROR = "PAY_ORDER_ERROR";
export const PAY_ORDER_RESET = "PAY_ORDER_RESET";

export const FETCH_ORDERS_LOADING = "FETCH_ORDERS_LOADING";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_ERROR = "FETCH_ORDERS_ERROR";
export const FETCH_ORDERS_RESET = "FETCH_ORDERS_RESET";

export const FETCH_ORDER_LOADING = "FETCH_ORDER_LOADING";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_ERROR = "FETCH_ORDER_ERROR";
export const FETCH_ORDER_RESET = "FETCH_ORDER_RESET";

export const FETCH_SELLER_ORDER_LOADING = "FETCH_SELLER_ORDER_LOADING";
export const FETCH_SELLER_ORDER_SUCCESS = "FETCH_SELLER_ORDER_SUCCESS";
export const FETCH_SELLER_ORDER_ERROR = "FETCH_SELLER_ORDER_ERROR";
export const FETCH_SELLER_ORDER_RESET = "FETCH_SELLER_ORDER_RESET";
