export const LATEST_PRODUCT_LOADING = 'LATEST_PRODUCT_LOADING'
export const LATEST_PRODUCT_SUCCESS = 'LATEST_PRODUCT_SUCCESS'
export const LATEST_PRODUCT_ERROR = 'LATEST_PRODUCT_ERROR'
export const LATEST_PRODUCT_RESET = 'LATEST_PRODUCT_RESET'
