export const LATEST_PRODUCT_LOADING = "LATEST_PRODUCT_LOADING";
export const LATEST_PRODUCT_SUCCESS = "LATEST_PRODUCT_SUCCESS";
export const LATEST_PRODUCT_ERROR = "LATEST_PRODUCT_ERROR";
export const LATEST_PRODUCT_RESET = "LATEST_PRODUCT_RESET";

export const SINGLE_PRODUCT_LOADING = "SINGLE_PRODUCT_LOADING";
export const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS";
export const SINGLE_PRODUCT_ERROR = "SINGLE_PRODUCT_ERROR";
export const SINGLE_PRODUCT_RESET = "SINGLE_PRODUCT_RESET";

export const ALL_PRODUCT_LOADING = "ALL_PRODUCT_LOADING";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_ERROR = "ALL_PRODUCT_ERROR";
export const ALL_PRODUCT_RESET = "ALL_PRODUCT_RESET";

export const PRODUCT_UPLOAD_LOADING = "PRODUCT_UPLOAD_LOADING";
export const PRODUCT_UPLOAD_SUCCESS = "PRODUCT_UPLOAD_SUCCESS";
export const PRODUCT_UPLOAD_ERROR = "PRODUCT_UPLOAD_ERROR";
export const PRODUCT_UPLOAD_RESET = "PRODUCT_UPLOAD_RESET";

export const CREATE_PRODUCT_LOADING = "CREATE_PRODUCT_LOADING";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";

export const YOUR_PRODUCT_LOADING = "YOUR_PRODUCT_LOADING";
export const YOUR_PRODUCT_SUCCESS = "YOUR_PRODUCT_SUCCESS";
export const YOUR_PRODUCT_ERROR = "YOUR_PRODUCT_ERROR";
export const YOUR_PRODUCT_RESET = "YOUR_PRODUCT_RESET";
